const swaggerJSDoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'PropertySerch.com API',
      version: '1.0.0',
      description:
        'API documentation for PropertySerch.com (Real Estate Transaction Operating System): Authentication & Access, Property Listings, Property Search, and Projects/Units (Builder) modules.',
    },
    servers: [
      {
        url: 'http://localhost:5000/api',
        description: 'Local development server',
      },
      {
        url: 'https://api.propertyserch.com/api',
        description: 'Production server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        Error: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string', example: 'Error message here' },
          },
        },
        RegisterRequest: {
          type: 'object',
          required: ['fullName', 'role'],
          properties: {
            fullName: { type: 'string', example: 'Rahul Sharma' },
            email: { type: 'string', format: 'email', example: 'rahul@example.com' },
            mobile: { type: 'string', example: '9876543210' },
            password: { type: 'string', format: 'password', example: 'Passw0rd!123' },
            role: {
              type: 'string',
              description:
                '`customer`/`broker` self-register with no token. `super_admin` self-registers with no token only while none exists yet (one-time bootstrap); afterwards, and for `admin`/`agency_admin`/`builder`/`internal_sales` always, a bearer token from a role permitted to create the target role is required (see the /auth/register endpoint description).',
              enum: [
                'customer',
                'broker',
                'agency_admin',
                'builder',
                'internal_sales',
                'admin',
                'super_admin',
              ],
              example: 'customer',
            },
            tenantId: {
              type: 'string',
              nullable: true,
              description: 'Required only when registering under an existing agency/builder tenant.',
              example: null,
            },
          },
        },
        RegisteredUser: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            full_name: { type: 'string', example: 'Rahul Sharma' },
            email: { type: 'string', example: 'rahul@example.com' },
            mobile: { type: 'string', example: '9876543210' },
            status: {
              type: 'string',
              enum: ['active', 'pending_approval'],
              example: 'active',
            },
            role: { type: 'string', example: 'customer' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        PropertyMedia: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            property_id: { type: 'string', format: 'uuid' },
            media_type: { type: 'string', enum: ['image', 'video'] },
            url: { type: 'string', example: 'https://cdn.example.com/property1.jpg' },
            display_order: { type: 'integer', example: 0 },
            is_primary: { type: 'boolean', example: true },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        Property: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            created_by: { type: 'string', format: 'uuid' },
            broker_id: { type: 'string', format: 'uuid', nullable: true },
            builder_id: { type: 'string', format: 'uuid', nullable: true },
            title: { type: 'string', example: '3BHK Sea View Apartment' },
            description: { type: 'string', nullable: true },
            property_type: {
              type: 'string',
              enum: ['apartment', 'villa', 'independent_house', 'plot', 'commercial', 'farmhouse', 'other'],
            },
            transaction_type: { type: 'string', enum: ['buy', 'sell', 'rent'] },
            price: { type: 'number', example: 8500000 },
            city: { type: 'string', example: 'Mumbai' },
            locality: { type: 'string', nullable: true, example: 'Bandra West' },
            address: { type: 'string', nullable: true },
            latitude: { type: 'number', nullable: true },
            longitude: { type: 'number', nullable: true },
            area_sqft: { type: 'number', nullable: true, example: 1250 },
            bedrooms: { type: 'integer', nullable: true, example: 3 },
            bathrooms: { type: 'integer', nullable: true, example: 2 },
            amenities: { type: 'array', items: { type: 'string' }, example: ['parking', 'gym', 'lift'] },
            status: {
              type: 'string',
              enum: ['draft', 'pending_approval', 'approved', 'rejected', 'inactive'],
            },
            rejection_reason: { type: 'string', nullable: true },
            approved_by: { type: 'string', format: 'uuid', nullable: true },
            approved_at: { type: 'string', format: 'date-time', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
            media: {
              type: 'array',
              items: { $ref: '#/components/schemas/PropertyMedia' },
            },
          },
        },
        PropertyCreateRequest: {
          type: 'object',
          required: ['title', 'propertyType', 'transactionType', 'price', 'city'],
          properties: {
            title: { type: 'string', example: '3BHK Sea View Apartment' },
            description: { type: 'string', example: 'Spacious 3BHK with a private balcony and sea view.' },
            propertyType: {
              type: 'string',
              enum: ['apartment', 'villa', 'independent_house', 'plot', 'commercial', 'farmhouse', 'other'],
              example: 'apartment',
            },
            transactionType: { type: 'string', enum: ['buy', 'sell', 'rent'], example: 'sell' },
            price: { type: 'number', example: 8500000 },
            city: { type: 'string', example: 'Mumbai' },
            locality: { type: 'string', example: 'Bandra West' },
            address: { type: 'string', example: '12 Carter Road' },
            latitude: { type: 'number', example: 19.0596 },
            longitude: { type: 'number', example: 72.8295 },
            areaSqft: { type: 'number', example: 1250 },
            bedrooms: { type: 'integer', example: 3 },
            bathrooms: { type: 'integer', example: 2 },
            amenities: { type: 'array', items: { type: 'string' }, example: ['parking', 'gym', 'lift'] },
            brokerId: { type: 'string', format: 'uuid', nullable: true },
            builderId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        PropertyUpdateRequest: {
          type: 'object',
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            propertyType: {
              type: 'string',
              enum: ['apartment', 'villa', 'independent_house', 'plot', 'commercial', 'farmhouse', 'other'],
            },
            transactionType: { type: 'string', enum: ['buy', 'sell', 'rent'] },
            city: { type: 'string' },
            locality: { type: 'string' },
            address: { type: 'string' },
            latitude: { type: 'number' },
            longitude: { type: 'number' },
            areaSqft: { type: 'number' },
            bedrooms: { type: 'integer' },
            bathrooms: { type: 'integer' },
            amenities: { type: 'array', items: { type: 'string' } },
          },
        },
        Project: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            builder_id: { type: 'string', format: 'uuid' },
            name: { type: 'string', example: 'Skyline Residency' },
            description: { type: 'string', nullable: true },
            city: { type: 'string', example: 'Pune' },
            locality: { type: 'string', nullable: true },
            address: { type: 'string', nullable: true },
            status: {
              type: 'string',
              enum: ['draft', 'upcoming', 'ongoing', 'completed', 'on_hold'],
            },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        ProjectCreateRequest: {
          type: 'object',
          required: ['name', 'city'],
          properties: {
            name: { type: 'string', example: 'Skyline Residency' },
            description: { type: 'string', example: 'A premium 2/3 BHK residential project.' },
            city: { type: 'string', example: 'Pune' },
            locality: { type: 'string', example: 'Baner' },
            address: { type: 'string', example: 'Baner Road' },
            builderId: {
              type: 'string',
              format: 'uuid',
              nullable: true,
              description: 'Required when the caller is admin/super_admin; defaults to the caller when they are a builder.',
            },
          },
        },
        ProjectUpdateRequest: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            description: { type: 'string' },
            city: { type: 'string' },
            locality: { type: 'string' },
            address: { type: 'string' },
            status: {
              type: 'string',
              enum: ['draft', 'upcoming', 'ongoing', 'completed', 'on_hold'],
            },
          },
        },
        Unit: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            project_id: { type: 'string', format: 'uuid' },
            unit_number: { type: 'string', example: 'A-1204' },
            floor: { type: 'integer', nullable: true, example: 12 },
            size: { type: 'number', nullable: true, example: 950 },
            price: { type: 'number', example: 6500000 },
            status: { type: 'string', enum: ['available', 'held', 'sold'] },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        UnitCreateRequest: {
          type: 'object',
          required: ['unitNumber', 'price'],
          properties: {
            unitNumber: { type: 'string', example: 'A-1204' },
            floor: { type: 'integer', example: 12 },
            size: { type: 'number', example: 950 },
            price: { type: 'number', example: 6500000 },
          },
        },
        UnitUpdateRequest: {
          type: 'object',
          properties: {
            unitNumber: { type: 'string' },
            floor: { type: 'integer' },
            size: { type: 'number' },
            price: { type: 'number' },
          },
        },
        Lead: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            created_by: { type: 'string', format: 'uuid', nullable: true },
            source: { type: 'string', enum: ['website', 'whatsapp', 'manual', 'campaign'] },
            property_id: { type: 'string', format: 'uuid', nullable: true },
            customer_id: { type: 'string', format: 'uuid' },
            assigned_to: { type: 'string', format: 'uuid', nullable: true },
            status: {
              type: 'string',
              enum: ['new', 'contacted', 'qualified', 'hot', 'warm', 'cold', 'won', 'lost'],
            },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        LeadCreateRequest: {
          type: 'object',
          required: ['customerId'],
          properties: {
            customerId: { type: 'string', format: 'uuid' },
            source: { type: 'string', enum: ['website', 'whatsapp', 'manual', 'campaign'], example: 'manual' },
            propertyId: { type: 'string', format: 'uuid', nullable: true },
            assignedTo: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        LeadUpdateRequest: {
          type: 'object',
          properties: {
            source: { type: 'string', enum: ['website', 'whatsapp', 'manual', 'campaign'] },
            propertyId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        PublicInquiryRequest: {
          type: 'object',
          required: ['fullName'],
          description: 'Either email or mobile must be provided.',
          properties: {
            fullName: { type: 'string', example: 'Anita Desai' },
            email: { type: 'string', format: 'email', example: 'anita@example.com' },
            mobile: { type: 'string', example: '9876543210' },
            propertyId: { type: 'string', format: 'uuid', nullable: true },
            message: { type: 'string', example: 'Interested in a 2BHK in Baner, budget up to 80L.' },
            source: { type: 'string', enum: ['website', 'whatsapp', 'manual', 'campaign'], example: 'website' },
          },
        },
        LeadNote: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            lead_id: { type: 'string', format: 'uuid' },
            user_id: { type: 'string', format: 'uuid' },
            note: { type: 'string' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        LeadActivityLogEntry: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            lead_id: { type: 'string', format: 'uuid' },
            user_id: { type: 'string', format: 'uuid', nullable: true },
            action: { type: 'string', example: 'status_changed' },
            details: { type: 'object', example: { from: 'new', to: 'contacted' } },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        Customer: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            user_id: { type: 'string', format: 'uuid', nullable: true },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            created_by: { type: 'string', format: 'uuid', nullable: true },
            full_name: { type: 'string', example: 'Anita Desai' },
            email: { type: 'string', nullable: true, example: 'anita@example.com' },
            mobile: { type: 'string', nullable: true, example: '9876543210' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        CustomerCreateRequest: {
          type: 'object',
          required: ['fullName'],
          description: 'Either email or mobile must be provided.',
          properties: {
            fullName: { type: 'string', example: 'Anita Desai' },
            email: { type: 'string', format: 'email', example: 'anita@example.com' },
            mobile: { type: 'string', example: '9876543210' },
            userId: {
              type: 'string',
              format: 'uuid',
              nullable: true,
              description: 'Link to an existing platform user account, if this customer also has one.',
            },
          },
        },
        CustomerUpdateRequest: {
          type: 'object',
          properties: {
            fullName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            mobile: { type: 'string' },
            userId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        CustomerPreferences: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            customer_id: { type: 'string', format: 'uuid' },
            budget_min: { type: 'number', nullable: true },
            budget_max: { type: 'number', nullable: true },
            preferred_locations: { type: 'array', items: { type: 'string' }, example: ['Baner', 'Wakad'] },
            property_type: {
              type: 'string',
              nullable: true,
              enum: ['apartment', 'villa', 'independent_house', 'plot', 'commercial', 'farmhouse', 'other'],
            },
            transaction_type: { type: 'string', nullable: true, enum: ['buy', 'sell', 'rent'] },
            bedrooms: { type: 'integer', nullable: true },
            notes: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        CustomerPreferencesRequest: {
          type: 'object',
          properties: {
            budgetMin: { type: 'number', example: 5000000 },
            budgetMax: { type: 'number', example: 8000000 },
            preferredLocations: { type: 'array', items: { type: 'string' }, example: ['Baner', 'Wakad'] },
            propertyType: {
              type: 'string',
              enum: ['apartment', 'villa', 'independent_house', 'plot', 'commercial', 'farmhouse', 'other'],
            },
            transactionType: { type: 'string', enum: ['buy', 'sell', 'rent'] },
            bedrooms: { type: 'integer', example: 2 },
            notes: { type: 'string', example: 'Prefers ground floor, needs parking for 2 cars.' },
          },
        },
        CustomerDocument: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            customer_id: { type: 'string', format: 'uuid' },
            deal_id: { type: 'string', format: 'uuid', nullable: true },
            document_url: { type: 'string', example: 'https://cdn.example.com/pan-card.pdf' },
            document_type: { type: 'string', nullable: true, example: 'pan_card' },
            uploaded_by: { type: 'string', format: 'uuid' },
            status: { type: 'string', enum: ['pending', 'approved', 'rejected'] },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        CustomerDocumentCreateRequest: {
          type: 'object',
          required: ['documentUrl'],
          properties: {
            documentUrl: { type: 'string', example: 'https://cdn.example.com/pan-card.pdf' },
            documentType: { type: 'string', example: 'pan_card' },
            dealId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        Task: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            title: { type: 'string', example: 'Follow up on site visit' },
            description: { type: 'string', nullable: true },
            related_entity_type: {
              type: 'string',
              nullable: true,
              enum: ['lead', 'customer', 'deal', 'property'],
            },
            related_entity_id: { type: 'string', format: 'uuid', nullable: true },
            assigned_to: { type: 'string', format: 'uuid', nullable: true },
            created_by: { type: 'string', format: 'uuid', nullable: true },
            due_date: { type: 'string', format: 'date-time' },
            priority: { type: 'string', enum: ['low', 'medium', 'high'] },
            status: { type: 'string', enum: ['pending', 'in_progress', 'completed', 'overdue'] },
            completed_at: { type: 'string', format: 'date-time', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        TaskCreateRequest: {
          type: 'object',
          required: ['title', 'dueDate'],
          properties: {
            title: { type: 'string', example: 'Follow up on site visit' },
            description: { type: 'string', example: 'Call customer to confirm Saturday 4pm slot' },
            relatedEntityType: { type: 'string', enum: ['lead', 'customer', 'deal', 'property'] },
            relatedEntityId: { type: 'string', format: 'uuid', nullable: true },
            assignedTo: { type: 'string', format: 'uuid', nullable: true },
            dueDate: { type: 'string', format: 'date-time', example: '2026-08-05T10:00:00Z' },
            priority: { type: 'string', enum: ['low', 'medium', 'high'], example: 'medium' },
          },
        },
        TaskUpdateRequest: {
          type: 'object',
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            relatedEntityType: { type: 'string', enum: ['lead', 'customer', 'deal', 'property'] },
            relatedEntityId: { type: 'string', format: 'uuid', nullable: true },
            assignedTo: { type: 'string', format: 'uuid', nullable: true },
            dueDate: { type: 'string', format: 'date-time' },
            priority: { type: 'string', enum: ['low', 'medium', 'high'] },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            user_id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            type: { type: 'string', example: 'task_assigned' },
            title: { type: 'string', example: 'New task assigned to you' },
            message: { type: 'string', nullable: true },
            related_entity_type: { type: 'string', nullable: true, example: 'task' },
            related_entity_id: { type: 'string', format: 'uuid', nullable: true },
            is_read: { type: 'boolean' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        SiteVisit: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            deal_id: { type: 'string', format: 'uuid' },
            scheduled_at: { type: 'string', format: 'date-time' },
            actual_visit_at: { type: 'string', format: 'date-time', nullable: true },
            status: { type: 'string', enum: ['scheduled', 'completed', 'cancelled', 'no_show'] },
            notes: { type: 'string', nullable: true },
            created_by: { type: 'string', format: 'uuid', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        DealStageHistoryEntry: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            deal_id: { type: 'string', format: 'uuid' },
            from_stage: {
              type: 'string',
              nullable: true,
              enum: ['inquiry', 'site_visit', 'negotiation', 'booking', 'documentation', 'payment', 'closed_won', 'closed_lost', 'on_hold'],
            },
            to_stage: {
              type: 'string',
              enum: ['inquiry', 'site_visit', 'negotiation', 'booking', 'documentation', 'payment', 'closed_won', 'closed_lost', 'on_hold'],
            },
            changed_by: { type: 'string', format: 'uuid', nullable: true },
            notes: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        Deal: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            lead_id: { type: 'string', format: 'uuid', nullable: true },
            customer_id: { type: 'string', format: 'uuid' },
            property_id: { type: 'string', format: 'uuid', nullable: true },
            unit_id: { type: 'string', format: 'uuid', nullable: true },
            broker_id: { type: 'string', format: 'uuid' },
            stage: {
              type: 'string',
              enum: ['inquiry', 'site_visit', 'negotiation', 'booking', 'documentation', 'payment', 'closed_won', 'closed_lost', 'on_hold'],
            },
            deal_value: { type: 'number', nullable: true, example: 8500000 },
            commission_amount: { type: 'number', nullable: true, example: 85000 },
            commission_percent: { type: 'number', nullable: true, example: 1 },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
            closed_at: { type: 'string', format: 'date-time', nullable: true },
            siteVisits: {
              type: 'array',
              items: { $ref: '#/components/schemas/SiteVisit' },
              description: 'Only present on GET /deals/{id}',
            },
            stageHistory: {
              type: 'array',
              items: { $ref: '#/components/schemas/DealStageHistoryEntry' },
              description: 'Only present on GET /deals/{id}',
            },
          },
        },
        DealCreateRequest: {
          type: 'object',
          description: 'customerId and brokerId can each be resolved from leadId if omitted directly.',
          properties: {
            leadId: { type: 'string', format: 'uuid', nullable: true },
            customerId: { type: 'string', format: 'uuid', nullable: true },
            propertyId: { type: 'string', format: 'uuid', nullable: true },
            unitId: { type: 'string', format: 'uuid', nullable: true },
            brokerId: { type: 'string', format: 'uuid', nullable: true },
            dealValue: { type: 'number', example: 8500000 },
            commissionAmount: { type: 'number', example: 85000 },
            commissionPercent: { type: 'number', example: 1 },
          },
        },
        DealUpdateRequest: {
          type: 'object',
          properties: {
            propertyId: { type: 'string', format: 'uuid', nullable: true },
            unitId: { type: 'string', format: 'uuid', nullable: true },
            brokerId: { type: 'string', format: 'uuid' },
            dealValue: { type: 'number' },
            commissionAmount: { type: 'number' },
            commissionPercent: { type: 'number' },
          },
        },
        Document: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            customer_id: { type: 'string', format: 'uuid', nullable: true },
            deal_id: { type: 'string', format: 'uuid', nullable: true },
            document_type: { type: 'string', enum: ['kyc', 'agreement', 'payment_receipt', 'noc', 'other'] },
            document_url: { type: 'string', example: 'https://cdn.example.com/agreement.pdf' },
            file_name: { type: 'string', nullable: true, example: 'sale-agreement.pdf' },
            uploaded_by: { type: 'string', format: 'uuid' },
            status: { type: 'string', enum: ['pending', 'approved', 'rejected'] },
            reviewed_by: { type: 'string', format: 'uuid', nullable: true },
            review_notes: { type: 'string', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        DocumentCreateRequest: {
          type: 'object',
          required: ['documentUrl'],
          properties: {
            documentUrl: { type: 'string', example: 'https://cdn.example.com/agreement.pdf' },
            documentType: { type: 'string', enum: ['kyc', 'agreement', 'payment_receipt', 'noc', 'other'], example: 'agreement' },
            fileName: { type: 'string', example: 'sale-agreement.pdf' },
            customerId: { type: 'string', format: 'uuid', nullable: true },
            dealId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        DocumentUpdateRequest: {
          type: 'object',
          properties: {
            documentType: { type: 'string', enum: ['kyc', 'agreement', 'payment_receipt', 'noc', 'other'] },
            documentUrl: { type: 'string' },
            fileName: { type: 'string' },
            customerId: { type: 'string', format: 'uuid', nullable: true },
            dealId: { type: 'string', format: 'uuid', nullable: true },
          },
        },
        Payment: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            deal_id: { type: 'string', format: 'uuid' },
            milestone_id: { type: 'string', format: 'uuid', nullable: true },
            customer_id: { type: 'string', format: 'uuid' },
            amount: { type: 'number', example: 500000 },
            currency: { type: 'string', example: 'INR' },
            gateway: { type: 'string', enum: ['razorpay', 'payu', 'manual'] },
            gateway_order_id: { type: 'string', nullable: true },
            gateway_payment_id: { type: 'string', nullable: true },
            gateway_signature: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['initiated', 'success', 'failed', 'refunded'] },
            initiated_by: { type: 'string', format: 'uuid', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        PaymentInitiateRequest: {
          type: 'object',
          required: ['dealId', 'customerId', 'amount'],
          properties: {
            dealId: { type: 'string', format: 'uuid' },
            customerId: { type: 'string', format: 'uuid' },
            milestoneId: { type: 'string', format: 'uuid', nullable: true },
            amount: { type: 'number', example: 500000 },
            currency: { type: 'string', example: 'INR' },
            gateway: { type: 'string', enum: ['razorpay', 'payu', 'manual'], example: 'razorpay' },
          },
        },
        PaymentWebhookRequest: {
          type: 'object',
          required: ['gatewayOrderId', 'gatewaySignature', 'status'],
          description: 'Shape of the payload a payment gateway would POST to the webhook.',
          properties: {
            gatewayOrderId: { type: 'string', example: 'stub_order_abc123' },
            gatewayPaymentId: { type: 'string', example: 'pay_xyz789' },
            gatewaySignature: { type: 'string', example: 'sig_mocked' },
            status: { type: 'string', enum: ['success', 'failed', 'refunded'] },
          },
        },
        Milestone: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            deal_id: { type: 'string', format: 'uuid' },
            milestone_name: { type: 'string', example: 'booking' },
            due_amount: { type: 'number', example: 500000 },
            due_date: { type: 'string', format: 'date-time' },
            status: { type: 'string', enum: ['pending', 'paid', 'overdue', 'waived'] },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time' },
          },
        },
        MilestoneCreateRequest: {
          type: 'object',
          required: ['dealId', 'milestoneName', 'dueAmount', 'dueDate'],
          properties: {
            dealId: { type: 'string', format: 'uuid' },
            milestoneName: { type: 'string', example: 'installment_1' },
            dueAmount: { type: 'number', example: 2000000 },
            dueDate: { type: 'string', format: 'date-time' },
          },
        },
        MilestoneUpdateRequest: {
          type: 'object',
          properties: {
            milestoneName: { type: 'string' },
            dueAmount: { type: 'number' },
            dueDate: { type: 'string', format: 'date-time' },
            status: { type: 'string', enum: ['pending', 'paid', 'overdue', 'waived'] },
          },
        },
        WhatsAppMessage: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tenant_id: { type: 'string', format: 'uuid', nullable: true },
            lead_id: { type: 'string', format: 'uuid', nullable: true },
            customer_id: { type: 'string', format: 'uuid', nullable: true },
            phone_number: { type: 'string', example: '9876543210' },
            direction: { type: 'string', enum: ['inbound', 'outbound'] },
            message_type: { type: 'string', enum: ['template', 'text', 'media'] },
            template_name: { type: 'string', nullable: true, example: 'lead_acknowledgement' },
            message_body: { type: 'string', nullable: true },
            provider_message_id: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['sent', 'delivered', 'read', 'failed'] },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        WhatsAppSendTemplateRequest: {
          type: 'object',
          required: ['leadId', 'templateName'],
          properties: {
            leadId: { type: 'string', format: 'uuid' },
            templateName: { type: 'string', example: 'property_share' },
            phoneNumber: { type: 'string', nullable: true, description: 'Defaults to the lead\'s customer mobile if omitted', example: '9876543210' },
          },
        },
        WhatsAppSharePropertyRequest: {
          type: 'object',
          required: ['leadId', 'propertyId'],
          properties: {
            leadId: { type: 'string', format: 'uuid' },
            propertyId: { type: 'string', format: 'uuid' },
            phoneNumber: { type: 'string', nullable: true },
          },
        },
        WhatsAppAcknowledgeLeadRequest: {
          type: 'object',
          required: ['leadId'],
          properties: {
            leadId: { type: 'string', format: 'uuid' },
            phoneNumber: { type: 'string', nullable: true },
          },
        },
        WhatsAppWebhookRequest: {
          type: 'object',
          required: ['type'],
          description: 'Simplified stand-in for Meta\'s real (deeply nested) webhook payload - see the TODO in whatsapp.service.js#handleWebhook.',
          properties: {
            type: { type: 'string', enum: ['message', 'status'], example: 'message' },
            phoneNumber: { type: 'string', example: '9876543210' },
            providerMessageId: { type: 'string', example: 'stub_wamid_abc123' },
            messageBody: { type: 'string', nullable: true, example: 'Is this still available?' },
            status: { type: 'string', enum: ['sent', 'delivered', 'read', 'failed'], nullable: true },
          },
        },
        AIInsight: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            lead_id: { type: 'string', format: 'uuid' },
            extracted_budget_min: { type: 'number', nullable: true },
            extracted_budget_max: { type: 'number', nullable: true },
            extracted_location: { type: 'string', nullable: true },
            extracted_property_type: { type: 'string', nullable: true },
            extracted_intent: { type: 'string', nullable: true },
            extracted_timeline: { type: 'string', nullable: true },
            summary: { type: 'string', nullable: true },
            score: { type: 'string', enum: ['hot', 'warm', 'cold'], nullable: true },
            confidence: { type: 'number', nullable: true, example: 0.82 },
            raw_response: { type: 'object' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        MatchResult: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            lead_id: { type: 'string', format: 'uuid', nullable: true },
            customer_id: { type: 'string', format: 'uuid' },
            property_id: { type: 'string', format: 'uuid' },
            relevance_score: { type: 'number', example: 85 },
            matched_reasons: {
              type: 'object',
              example: { locationMatch: true, budgetFit: 'within_range', typeMatch: true, transactionMatch: true },
            },
            created_at: { type: 'string', format: 'date-time' },
            property: { $ref: '#/components/schemas/Property' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: ['./src/routes/*.js'],
};

module.exports = swaggerJSDoc(options);